name: Build driver solution
on:
  push:
    branches:
      - main
jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug] #, Release
        platform: [x64]
    runs-on: windows-2022 #2019安装WDK不太顺利。
    env:
      Solution_Path: .\trunk\HidePort.sln
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.3.1
        
      - name: Restore NuGet packages
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: nuget restore .\trunk
        
        #谨记：这个只需运行一次即可。
      #- name: Install WDK #这个执行半个小时是要的。
      #  working-directory: ${{env.GITHUB_WORKSPACE}}
      #  run: .\.github\workflows\Install-WDK.ps1 #microsoft\runner-images\images\win\scripts\Installers\Install-WDK.ps1

      - name: Build solution
        run: msbuild /m  /p:Configuration=${{ env.Configuration }} /p:Platform=${{ env.Platform }} ${{ env.Solution_Path }}
        env:
          Configuration: ${{ matrix.configuration }}
          Platform: ${{ matrix.platform }}
